### ISSUE TITLE
from bytes

### ISSUE THREAD

**Issue by minisbett** [MaxOhn/rosu-pp#10]
Why is there no option to parse a beatmap from bytes instead of a file?? so much more useful in so many scenarios

**Comment by MaxOhn** [comment]
There is [Beatmap::parse](https://docs.rs/rosu-pp/latest/rosu_pp/parse/struct.Beatmap.html#method.parse) which you can give anything that implements `std::io::Read` or the analogous async trait so you can give it bytes.

**Comment by minisbett** [comment]
oh that's good to know, thanks for telling me
