### ISSUE TITLE
maxCombo

### ISSUE THREAD

**Issue by Mxnuuel** [MaxOhn/rosu-pp#11]
i'm using the js-wrapper for rosu-pp and i'm trying to get the maxCombo value from the beatmap calculation.
is that somehow possible to recieve the maxCombo out of the .osu file with the calculate method?
because there is a documentation inside that showes maxCombo as value but when i look on the response i don't have that.
it would really help me a lot having that!
[Docs](https://x.catboy.best/iPQdAYM.png)
[Response](https://x.catboy.best/cXW5mQG.png)

**Comment by MaxOhn** [comment]
Max combo is available for all modes except for mania. Just checked and it works for me.
If you have a non-mania map for which it doesn't show max combo let me know the map id so I can test and fix.

**Comment by Mxnuuel** [comment]
i'm an idiot just having misstyped the "maxCombo" to maxcombo. I'm sorry about this, but thank you for your answer :)
