### ISSUE TITLE
ctb pp for hidden mod incorrect

### ISSUE THREAD

**Issue by cyperdark** [MaxOhn/rosu-pp#3]
```
id: 2857854
mods=24
acc=100
miss=0
combo=261
```
My result: https://i.imgur.com/5kQa6Ph.jpeg
on osu: https://i.imgur.com/KsLksKT.jpeg

```
id: 3178954
mods=8
acc=98.87
miss=8
combo=447
```
My result: https://i.imgur.com/T8F80Cy.jpeg
on osu: https://i.imgur.com/bR2ofK0.jpeg

**Comment by cyperdark** [comment]
oops i did mistake in my program

**Comment by cyperdark** [comment]
or it's not mine code: https://i.imgur.com/VQTZ9Yj.jpeg
result: https://i.imgur.com/eLEMsbt.jpeg

**Comment by MaxOhn** [comment]
Thanks for letting me know, I'll try to look into it soon.

**Comment by cyperdark** [comment]
i guess i find mistake, i didn't add ``.mods`` to second recalculation, sorry my mistake. 
![image](https://user-images.githubusercontent.com/21735205/134619345-930279ff-e5b4-47f7-bbdb-a762aae8eb16.png)
