### ISSUE TITLE
`GradualPerformance.next()` does not work properly with `lazer(true)`

### ISSUE THREAD

**Issue by HollisMeynell** [MaxOhn/rosu-pp#47]
call `next()` until the calculation is finished, the final result is less than the direct calculation, if this is the expected behavior, I close the PR.

**Comment by MaxOhn** [comment]
My test for it is currently passing
https://github.com/MaxOhn/rosu-pp/blob/48414de0174bdc405819a205e8a8d32b67349756/src/osu/performance/gradual.rs#L171-L181

Can you give a small example or maybe just a map id I should test with?

**Comment by MaxOhn** [comment]
The reason the pp values differ is because you only increment `n300` which is sufficient on stable but with lazer set to `true` you also need to specify `osu_large_tick_hits` and `slider_end_hits`.

Similarly, osu!mania requires two hitresults per hold note or the values won't match. Only osu!taiko and osu!catch work the same with and without lazer.

**Comment by HollisMeynell** [comment]
Thanks for your response! I have another question to ask. I'd like to know why you use `mut self` instead of `&mut self` when setting properties in `Difficulty` or `Performance`. I'm writing a dynamic library and need to use `Box` to obtain raw pointers, so every modification requires an additional `Box::new()`.

**Comment by MaxOhn** [comment]
> I'd like to know why you use `mut self` instead of `&mut self` when setting properties in `Difficulty` or `Performance`.

There's a few minor reasons for that
- `&mut` wouldn't allow some of the methods to be `const`
- Methods like `Difficulty::gradual_difficulty` require ownership so using it like `Difficulty::new().mods(0).gradual_difficulty(map)` wouldn't work
- I prefer using the same pattern for all builders so it would preferably need to be a change to `&mut` for all builders which amplifies the first two points

I'm not entirely against the `&mut` builder pattern here but I don't quite think I have enough reason to change it.

> I'm writing a dynamic library and need to use `Box` to obtain raw pointers, so every modification requires an additional `Box::new()`.

The builder pattern can indeed be quite annoying across FFI and such. What I could recommend is either
- provide one method that takes all optional parameters at once
- don't store parameters directly in a `Difficulty` but instead use a new field for each parameter and only create the `Difficulty` at the end

**Comment by HollisMeynell** [comment]
Thanks
