### ISSUE TITLE
Add option to change beatmaps difficulty settings

### ISSUE THREAD

**Issue by respektive** [MaxOhn/rosu-pp#7]
Would be cool to be able to change AR, OD etc. without editing the .osu file before parsing with rosu-pp.  
Another good addition would be being able to also change the "speed rate" of the map. e.g. setting it to something like 1.2x instead of being limited to only DT/HT or 1.5x/0.75x respectively.

**Comment by MaxOhn** [comment]
Attributes like AR and OD are public fields in the `Beatmap` struct so after parsing you can adjust their values.

Customizable clock rates sound alright. They require a little bit of restructuring of the user interface for difficulty calculation but I think that was overdue anyway.

**Comment by respektive** [comment]
> Attributes like AR and OD are public fields in the `Beatmap` struct so after parsing you can adjust their values.

I probably should have stated that I'm using rosu-pp-js. Is that something that's also doable there? If so I wasn't able to figure out how. The readme only states the path field and changing the map attributes in the params doesn't work.
> Customizable clock rates sound alright. They require a little bit of restructuring of the user interface for difficulty calculation but I think that was overdue anyway.

Main reason I'm bringing this up is for calculating pp on lazer scores using custom rates. So this would be really helpful

**Comment by MaxOhn** [comment]
> I probably should have stated that I'm using rosu-pp-js. Is that something that's also doable there? If so I wasn't able to figure out how. The readme only states the path field and changing the map attributes in the params doesn't work.

Oh yeah in there it's not currently possible.
I didn't really plan on extending rosu-pp-js functionality but simply accepting a few more fields for the params is really easy to do so I guess I can do that 👍

**Comment by respektive** [comment]
> Oh yeah in there it's not currently possible. I didn't really plan on extending rosu-pp-js functionality but simply accepting a few more fields for the params is really easy to do so I guess I can do that :+1: 

should also add it to the python bindings then :smile: :+1:

**Comment by respektive** [comment]
Can be closed as of version v0.5.1 :+1:
